# Generated by Django 5.2.11 on 2026-02-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('value', models.JSONField()),
                ('type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('boolean', 'Boolean'), ('json', 'JSON')], default='string', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'settings',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('telegram_uid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('language_code', models.CharField(blank=True, max_length=15, null=True)),
                ('is_premium', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
                'indexes': [models.Index(fields=['language_code'], name='users_languag_50ffd2_idx'), models.Index(fields=['is_premium'], name='users_is_prem_41b83a_idx'), models.Index(fields=['username'], name='users_usernam_baeb4b_idx')],
            },
        ),
    ]
