# Generated by Django 5.2.11 on 2026-02-08 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_telegram_uid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=255)),
                ('place_of_living', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_profiles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Horoscope',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_telegram_uid', models.BigIntegerField()),
                ('horoscope_type', models.CharField(choices=[('daily', 'Daily'), ('first', 'First (onboarding)')], default='daily', max_length=50)),
                ('date', models.DateField()),
                ('full_text', models.TextField()),
                ('teaser_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'horoscopes',
                'managed': True,
                'indexes': [models.Index(fields=['user_telegram_uid', 'date'], name='horoscopes_user_te_0919ca_idx'), models.Index(fields=['user_telegram_uid', 'horoscope_type', 'date'], name='horoscopes_user_te_84576c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_telegram_uid', models.BigIntegerField(unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('telegram_payment_charge_id', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'subscriptions',
                'managed': True,
                'indexes': [models.Index(fields=['user_telegram_uid', 'status'], name='subscriptio_user_te_c53d56_idx'), models.Index(fields=['status', 'expires_at'], name='subscriptio_status_b3f3e1_idx')],
            },
        ),
    ]
