# Generated by Django 5.2.11 on 2026-02-08 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horoscope', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
