# Generated by Django 5.2.11 on 2026-02-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horoscope', '0002_subscription_reminder_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('uk', 'Ukrainian'), ('de', 'German')], default='en', max_length=5),
        ),
    ]
