# Generated by Django 5.2.11 on 2026-02-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horoscope', '0003_userprofile_preferred_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='horoscope',
            name='failed_to_send_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horoscope',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
