# Generated by Django 5.2.11 on 2026-02-14 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horoscope', '0004_horoscope_failed_to_send_at_horoscope_sent_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horoscope',
            options={},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
        migrations.RenameIndex(
            model_name='horoscope',
            new_name='horoscope_h_user_te_c5b07b_idx',
            old_name='horoscopes_user_te_0919ca_idx',
        ),
        migrations.RenameIndex(
            model_name='horoscope',
            new_name='horoscope_h_user_te_a847ef_idx',
            old_name='horoscopes_user_te_84576c_idx',
        ),
        migrations.RenameIndex(
            model_name='subscription',
            new_name='horoscope_s_user_te_bc0667_idx',
            old_name='subscriptio_user_te_c53d56_idx',
        ),
        migrations.RenameIndex(
            model_name='subscription',
            new_name='horoscope_s_status_2b6c16_idx',
            old_name='subscriptio_status_b3f3e1_idx',
        ),
        migrations.AlterModelTable(
            name='horoscope',
            table=None,
        ),
        migrations.AlterModelTable(
            name='subscription',
            table=None,
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table=None,
        ),
    ]
