# Generated by Django 5.2.11 on 2026-02-14 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horoscope', '0005_alter_horoscope_options_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMUsage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=256)),
                ('input_tokens', models.PositiveIntegerField()),
                ('output_tokens', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('horoscope', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='llm_usage', to='horoscope.horoscope')),
            ],
        ),
    ]
