# Generated by Django 5.2.11 on 2026-02-14 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horoscope', '0006_llmusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='horoscope',
            name='extended_teaser_text',
            field=models.TextField(default=''),
        ),
    ]
