# Generated by Django 5.2.11 on 2026-02-14 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horoscope', '0007_horoscope_extended_teaser_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoroscopeFollowup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('answer_text', models.TextField()),
                ('model', models.CharField(max_length=256)),
                ('input_tokens', models.PositiveIntegerField()),
                ('output_tokens', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('horoscope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='horoscope.horoscope')),
            ],
            options={
                'indexes': [models.Index(fields=['horoscope'], name='horoscope_h_horosco_ce825b_idx')],
            },
        ),
    ]
