# Generated by Django 5.2.11 on 2026-02-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horoscope', '0008_horoscopefollowup'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birth_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
