# Generated by Django 5.2.11 on 2026-02-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horoscope', '0009_userprofile_birth_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notification_hour_utc',
            field=models.IntegerField(blank=True, help_text='Hour (0-23) in UTC when user wants to receive notifications. Overrides per-language default.', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(blank=True, default='', help_text='UTC offset string, e.g. "UTC+3", "UTC-5", "UTC+0"', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('uk', 'Ukrainian'), ('de', 'German'), ('hi', 'Hindi'), ('ar', 'Arabic'), ('it', 'Italian'), ('fr', 'French')], default='en', max_length=5),
        ),
    ]
