# Generated by Django 5.2.11 on 2026-02-14 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('from_user_telegram_uid', models.BigIntegerField()),
                ('to_user_telegram_uid', models.BigIntegerField(blank=True, null=True)),
                ('chat_telegram_uid', models.BigIntegerField()),
                ('text', models.TextField(blank=True, null=True)),
                ('callback_query', models.CharField(blank=True, max_length=255, null=True)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('context', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['from_user_telegram_uid', 'created_at'], name='telegram_bo_from_us_b50c12_idx'), models.Index(fields=['chat_telegram_uid', 'created_at'], name='telegram_bo_chat_te_3acaf2_idx'), models.Index(fields=['created_at'], name='telegram_bo_created_8d565a_idx'), models.Index(fields=['callback_query'], name='telegram_bo_callbac_6b7937_idx')],
            },
        ),
    ]
